"""add desc

Revision ID: 69c2b5e6a473
Revises: e47427691255
Create Date: 2022-06-19 16:31:35.373384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c2b5e6a473'
down_revision = 'e47427691255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Product', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Product', 'description')
    # ### end Alembic commands ###
