"""add price

Revision ID: e47427691255
Revises: 8ca3dd2e4424
Create Date: 2022-06-19 16:05:18.736930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47427691255'
down_revision = '8ca3dd2e4424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Product', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Product', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
