# Generated by Django 4.0.5 on 2022-07-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox', '0004_commondata_dev_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commondata',
            name='dev_type',
        ),
    ]
