# Generated by Django 4.0.5 on 2022-07-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox', '0005_remove_commondata_dev_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commondata',
            name='manufactured',
            field=models.CharField(choices=[('Arista', 'Arista'), ('Cisco', 'Cisco'), ('Mellanox', 'Mellanox')], max_length=20),
        ),
    ]
