# Generated by Django 4.0.5 on 2022-07-03 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox', '0011_vendor_remove_commondata_manufactured'),
    ]

    operations = [
        migrations.AddField(
            model_name='commondata',
            name='manufactured',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox.vendor'),
        ),
    ]
