# Generated by Django 4.0.5 on 2022-07-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox', '0003_rename_sn_commondata_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='commondata',
            name='dev_type',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
