# Generated by Django 4.0.5 on 2022-07-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox', '0010_commondata_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufactured', models.CharField(choices=[('Arista', 'Arista'), ('Cisco', 'Cisco'), ('Mellanox', 'Mellanox'), ('Juniper', 'Juniper')], max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='commondata',
            name='manufactured',
        ),
    ]
