# Generated by Django 4.0.5 on 2022-07-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufactured', models.CharField(max_length=15)),
                ('model_name', models.CharField(max_length=20)),
                ('sn', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=100)),
            ],
        ),
    ]
