# Generated by Django 4.0.5 on 2022-07-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox', '0013_alter_vendor_manufactured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='commondata_ptr',
        ),
        migrations.DeleteModel(
            name='Router',
        ),
        migrations.DeleteModel(
            name='Switch',
        ),
    ]
