# Generated by Django 4.0.5 on 2022-07-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox', '0014_remove_switch_commondata_ptr_delete_router_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=10)),
                ('model_name', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('dev_type', models.CharField(choices=[('Router', 'Router'), ('Switch', 'Switch')], max_length=30)),
                ('manufactured', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox.vendor')),
            ],
        ),
    ]
