# Generated by Django 4.0.5 on 2022-07-11 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox', '0015_devices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devices',
            new_name='Device',
        ),
    ]
