# Generated by Django 4.0.5 on 2022-07-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox', '0016_rename_devices_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonData',
        ),
    ]
