# Generated by Django 4.0.5 on 2022-07-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox', '0017_delete_commondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
