# Generated by Django 4.0.5 on 2022-07-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox', '0021_site_device_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='address',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='full_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
