version: "3"

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: hw4
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /mnt/f/dev/py/venv/otus/homework_04/db
    volumes:
      - hw4-pg-data:/mnt/f/dev/py/venv/otus/homework_04/db
    ports:
      - "5432:5432"

volumes:
  hw4-pg-data: